import { OfferType } from '@goldenhippo/builder-cart-schemas';
import { CommerceOffer } from './types';

export const MOCK_OFFERS: CommerceOffer[] = [
  {
    type: OfferType.Upsell,
    id: 'a0f5f00000UP001AAAB',
    description: '<p>Add a second bottle and <strong>save 25%</strong> — never run out.</p>',
    retailPrice: 59.95,
    localeRetailPrice: 59.95,
    salePrice: 44.96,
    localeSalePrice: 44.96,
    tax: 3.15,
    localeTax: 3.15,
    includesTax: false,
    product: {
      id: 'a0P5f00000PR001AAAB',
      name: 'Total Restore 60ct - Single Bottle Upsell',
      description: 'Gut health support formula, 60 capsules.',
      image: {
        url: 'https://cdn.goldenhippo.com/mock/total-restore-1.png',
        alt: 'Total Restore bottle',
      },
      taxCode: 'P0000000',
      packaging: 'Bottle',
      quantity: 1,
      friendlyName: 'Total Restore',
      familyId: 'a0F5f00000FA001AAAB',
    },
    subscription: false,
  },
  {
    type: OfferType.Upsell,
    id: 'a0f5f00000UP002AAAB',
    description: '<p>Subscribe &amp; save — <strong>3 bottles every 90 days</strong> at your lowest price.</p>',
    retailPrice: 179.85,
    localeRetailPrice: 179.85,
    salePrice: 119.9,
    localeSalePrice: 119.9,
    tax: 8.39,
    localeTax: 8.39,
    includesTax: false,
    product: {
      id: 'a0P5f00000PR002AAAB',
      name: 'Total Restore 60ct - 3 Pack Subscription Upsell',
      description: 'Gut health support formula, 3 bottles, auto-shipped quarterly.',
      image: {
        url: 'https://cdn.goldenhippo.com/mock/total-restore-3.png',
        alt: 'Total Restore three-pack',
      },
      taxCode: 'P0000000',
      packaging: 'Bottle',
      quantity: 3,
      friendlyName: 'Total Restore 3-Pack',
      familyId: 'a0F5f00000FA001AAAB',
    },
    subscription: true,
  },
  {
    type: OfferType.Downsell,
    id: 'a0f5f00000DS001AAAB',
    description: '<p>Not ready for three? Grab a <strong>single bottle</strong> at the same per-bottle price.</p>',
    retailPrice: 59.95,
    localeRetailPrice: 59.95,
    salePrice: 39.97,
    localeSalePrice: 39.97,
    tax: 2.8,
    localeTax: 2.8,
    includesTax: false,
    product: {
      id: 'a0P5f00000PR001AAAB',
      name: 'Total Restore 60ct - Single Bottle Downsell',
      description: 'Gut health support formula, 60 capsules.',
      taxCode: 'P0000000',
      packaging: 'Bottle',
      quantity: 1,
      friendlyName: 'Total Restore',
      familyId: 'a0F5f00000FA001AAAB',
    },
    subscription: false,
  },
  {
    type: OfferType.Upsell,
    id: 'a0f5f00000UP003AAAB',
    description: '<p>Complete your routine with our <strong>Omega-3</strong> — includes VAT.</p>',
    retailPrice: 49.95,
    localeRetailPrice: 42.5,
    salePrice: 34.95,
    localeSalePrice: 29.73,
    tax: 5.95,
    localeTax: 5.06,
    includesTax: true,
    product: {
      id: 'a0P5f00000PR003AAAB',
      name: 'Ultra Omega 90ct - Cross-sell Upsell',
      description: 'High-potency fish oil, 90 softgels.',
      image: {
        url: 'https://cdn.goldenhippo.com/mock/ultra-omega.png',
        alt: 'Ultra Omega bottle',
      },
      taxCode: 'P0000000',
      packaging: 'Bottle',
      quantity: 1,
      friendlyName: 'Ultra Omega',
      familyId: 'a0F5f00000FA002AAAB',
    },
    subscription: false,
  },
];

/** Look a mock offer up by its Salesforce id — mirrors a future `getOfferById`. */
export const findMockOffer = (id: string): CommerceOffer | undefined => MOCK_OFFERS.find((offer) => offer.id === id);
